[[plugins]]
repo = 'shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'cespare/vim-toml'

# IDE
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'townk/vim-autoclose'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'alvan/vim-closetag'

# web
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'vim-ruby/vim-ruby'
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'chase/vim-ansible-yaml'
